name: VMware Harbor Registry Deployment On AWS Using Terraform And Ansible

on: [push]

jobs:
  build:
    name: Deploying Harbor registry
    runs-on: ubuntu-latest

    steps:
    - uses: docker://arunalakmal/terransible-aws:1.0
    - name: Setting Up Keys
      env:
        IRONMANSSH: ${{ secrets.IRONMANSSH }}
        IRONMANPUBSSH: ${{ secrets.IRONMANSSH }}
      run: |
        chmod +x initialsetup.sh,
        sh ../../initialsetup.sh,
        rm -rf .terraform,
        terraform --version,
        terraform init
    - name: Harbor Deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform validate,
        terraform plan -out "hbrdeploy",
        terraform apply -input=false "hbrdeploy",
        export ANSIBLE_HOST_KEY_CHECKING=False,
        ansible-playbook -i harbor_hosts ansible-docker-deploy.yaml,
        ansible-playbook -i harbor_hosts harbor-ansible-playbook.yaml
